rec_valor_complemento.Call( & empresa_syj_id, empleado_codigo, 'FD_CUENTA', TipoComplemento.Empleado, & FD_CUENTA, & error, & mensaje)
recupera_res_acu.Call( & empresa_syj_id, & liquidacion_caratula_id, empleado_codigo, 'ACU.SJ_BASICO', 'N', & nSJ_BASICO, & resumen_acum_cvalor, & error, & mensaje)
recupera_res_acu.Call( & empresa_syj_id, & liquidacion_caratula_id, empleado_codigo, 'TOT.TH', 'N', & nTH, & resumen_acum_cvalor, & error, & mensaje)
recupera_res_acu.Call( & empresa_syj_id, & liquidacion_caratula_id, empleado_codigo, 'TOT.HORASREM', 'N', & nHORASREM, & resumen_acum_cvalor, & error, & mensaje)
recupera_res_acu.Call( & empresa_syj_id, & liquidacion_caratula_id, empleado_codigo, 'TOT.FONDO', 'N', & nFONDO, & resumen_acum_cvalor, & error, & mensaje)
recupera_res_acu.Call( & empresa_syj_id, & liquidacion_caratula_id, empleado_codigo, 'ACU.BASE_FDD', 'N', & nBASE_FDD, & resumen_acum_cvalor, & error, & mensaje)
recupera_res_acu.Call( & empresa_syj_id, & liquidacion_caratula_id, empleado_codigo, 'ACU.FDPOR', 'N', & nFDPOR, & resumen_acum_cvalor, & error, & mensaje)
recupera_res_acu.Call( & empresa_syj_id, & liquidacion_caratula_id, empleado_codigo, 'ACU.CP_FDD', 'N', & nCP_FDD, & resumen_acum_cvalor, & error, & mensaje)
recupera_res_acu.Call( & empresa_syj_id, & liquidacion_caratula_id, empleado_codigo, 'ACU.FDFON', 'N', & nFDFON, & resumen_acum_cvalor, & error, & mensaje)
recupera_res_acu.Call( & empresa_syj_id, & liquidacion_caratula_id, empleado_codigo, 'ACU.CP_FCD', 'N', & nCP_FCD, & resumen_acum_cvalor, & error, & mensaje)
recupera_res_acu.Call( & empresa_syj_id, & liquidacion_caratula_id, empleado_codigo, 'ACU.CP_RNIC', 'N', & nCP_RNIC, & resumen_acum_cvalor, & error, & mensaje)
recupera_res_acu.Call( & empresa_syj_id, & liquidacion_caratula_id, empleado_codigo, 'ACU.CP_FODECO', 'N', & nCP_FODECO, & resumen_acum_cvalor, & error, & mensaje)
